version: 2.1

executors:
  mac:
    macos:
      xcode: 26.0.0
    resource_class: m4pro.medium

jobs:
  build-react-native:
    executor: mac
    steps:
      - checkout
      - run:
          name: Build React Native SDK
          command: ./scripts/build_react_native.sh

workflows:
  version: 2
  react-native-build:
    jobs:
      - build-react-native
